version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: env_demo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-multiple-db.sql:/docker-entrypoint-initdb.d/init-multiple-db.sql

volumes:
  pg_data:
