server:
  port: 8081
spring:
  application:
    name: Multiple-Env-Demo
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update